"""
LLM Libraries — Shared utilities for 6-library deep-dive notebooks.
"""

from src.config import (
    ANTHROPIC_API_KEY,
    BRAINTRUST_API_KEY,
    DSPY_OPTIMIZER_TRIALS,
    GOOGLE_API_KEY,
    GROQ_API_KEY,
    INSTRUCTOR_MAX_RETRIES,
    MISTRAL_API_KEY,
    OLLAMA_BASE_URL,
    OPENAI_API_KEY,
    REDTEAM_SAMPLE_SIZE,
    SAMPLE_SIZE,
    USE_OLLAMA,
    USE_SMALL_MODEL,
    get_anthropic_client,
    get_anthropic_model,
    get_dspy_lm,
    get_instructor_client,
    get_openai_client,
    get_openai_model,
    print_config,
)
from src.cost_tracker import estimate_cost, full_report, print_cost_warning
from src.datasets import (
    ensure_datasets,
    generate_invoice_texts,
    generate_math_problems,
    generate_qa_pairs,
    generate_rag_contexts,
    generate_sentiment_data,
    load_jsonl,
    save_jsonl,
)
from src.metrics import (
    contains_match,
    dspy_contains_match,
    dspy_exact_match,
    dspy_f1_metric,
    dspy_length_constraint,
    exact_match,
    f1_score,
    promptfoo_contains,
    promptfoo_is_json,
    promptfoo_latency,
    promptfoo_llm_rubric,
    promptfoo_not_contains,
    promptfoo_regex,
    validate_invoice_total,
    word_count_score,
)

__all__ = [
    # Config
    "USE_OLLAMA",
    "USE_SMALL_MODEL",
    "OLLAMA_BASE_URL",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "BRAINTRUST_API_KEY",
    "GOOGLE_API_KEY",
    "MISTRAL_API_KEY",
    "GROQ_API_KEY",
    "SAMPLE_SIZE",
    "DSPY_OPTIMIZER_TRIALS",
    "INSTRUCTOR_MAX_RETRIES",
    "REDTEAM_SAMPLE_SIZE",
    "get_openai_model",
    "get_anthropic_model",
    "get_dspy_lm",
    "get_instructor_client",
    "get_openai_client",
    "get_anthropic_client",
    "print_config",
    # Cost tracker
    "estimate_cost",
    "print_cost_warning",
    "full_report",
    # Datasets
    "ensure_datasets",
    "generate_qa_pairs",
    "generate_math_problems",
    "generate_sentiment_data",
    "generate_invoice_texts",
    "generate_rag_contexts",
    "load_jsonl",
    "save_jsonl",
    # Metrics
    "exact_match",
    "contains_match",
    "f1_score",
    "dspy_exact_match",
    "dspy_contains_match",
    "dspy_f1_metric",
    "dspy_length_constraint",
    "word_count_score",
    "promptfoo_contains",
    "promptfoo_not_contains",
    "promptfoo_regex",
    "promptfoo_is_json",
    "promptfoo_llm_rubric",
    "promptfoo_latency",
    "validate_invoice_total",
]
